chore:fix husky config

diff --git a/.husky/comimt-msg b/.husky/comimt-msg
--- a/.husky/comimt-msg
+++ b/.husky/comimt-msg
@@ -1,5 +1,8 @@
-# Run commitlint. If it fails (||), run the code inside the brackets.
-npx --no -- commitlint --edit ${1} || {
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
+# Run commitlint. If it fails (||), run the custom error message.
+npx --no -- commitlint --edit "${1}" || {
     echo ""
     echo "---------------------------------------------------------------------"
     echo "🚨 COMMIT REJECTED: Invalid Message Format"
